---
- name: "Attach environment to application"
  template:
    src: "dotenv.j2"
    dest: "{{ application_prefix }}/{{ application_name }}/shared/.env"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0644
  become: True
  register: _app_env_updated
