---
- name: "Attach environment to application"
  template:
    src: "dotenv.j2"
    dest: "{{ application_prefix }}/{{ application_name }}/shared/.env"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0644
  become: True
  become_user: "{{ application_user }}"
  notify: restart application

- name: "Export envvars (bash)"
  template:
    src: "load_app_env.sh.j2"
    dest: "/etc/profile.d/load_app_env.sh"
    owner: "root"
    group: "root"
    mode: 0755
  become: True
