---
- name: "Create application directory"
  file:
    path: "{{ application_prefix }}/{{ application_name }}/releases/{{ timestamp.stdout }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0775

- name: "Get project archive"
  get_url:
    url: "{{ application_url }}"
    dest: "{{ application_prefix }}/{{ application_name }}/releases/{{ timestamp.stdout }}/"
    headers: "{{ application_url_headers | default(omit) }}"
  become_user: "{{ application_user }}"
