---
- name: "Get the current time for a timestamp"
  command: "date +%Y%m%d-%H%M%S"
  register: timestamp
  tags: [application-deploy, application]

- name: "Create application directories"
  file:
    path: "{{ application_prefix }}/{{ application_name }}/{{ item }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0775
  with_items:
    - releases
    - shared
  tags: [application]

- name: "Get list of previous releases"
  shell: "ls -t {{ application_prefix }}/{{ application_name }}/releases | tail -n +{{ application_keep_versions }}"
  args:
    executable: /bin/bash
  register: release_dirs
  tags: [application, application-deploy, application-cleanup]

- name: "Create additional shared directories"
  file:
    path: "{{ application_prefix }}/{{ application_name }}/shared/{{ item.src }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0775
  when: item.dir is defined
  with_items: "{{ application_shared }}"
  tags: [application-deploy, application]

- include: environ.yml
  when: application_environment | length > 0
  tags: [application-deploy, application-env, application]

- include: from_repo.yml
  when: application_repository | length > 0
  tags: [application-deploy, application]

- include: from_url.yml
  when: application_url | length > 0
  tags: [application-deploy, application]

- name: "Link shared resources to the application"
  file:
    src: "{{ application_prefix }}/{{ application_name }}/shared/{{ item.src }}"
    dest: "{{ application_prefix }}/{{ application_name }}/releases/{{ timestamp.stdout }}/{{ item.dest }}"
    state: link
    force: yes
  notify: restart application
  when: item.dest is defined
  become_user: "{{ application_user }}"
  with_items: "{{ application_shared }}"
  tags: [application-deploy, application]

- name: "Prepare the application"
  shell: "/bin/bash -lc '{{ item }}'"
  args:
    chdir: "{{ application_prefix }}/{{ application_name }}/releases/{{ timestamp.stdout }}"
  notify: restart application
  become_user: "{{ application_user }}"
  with_items: "{{ application_prepare }}"
  tags: [application-deploy, application]

- name: "Link deployed application to current directory"
  file:
    src: "{{ application_prefix }}/{{ application_name }}/releases/{{ timestamp.stdout }}"
    dest: "{{ application_prefix }}/{{ application_name }}/current"
    state: link
    force: yes
  notify: restart application
  become_user: "{{ application_user }}"
  tags: [application-deploy, application]

- name: "Cleanup"
  file:
    name: "{{ application_prefix }}/{{ application_name }}/releases/{{ item }}"
    state: absent
  with_items: "{{ release_dirs.stdout_lines }}"
  when: release_dirs.stdout != ""
  tags: [application-deploy, application, application-cleanup]
