---
- name: "Install requirements"
  apt:
    name: "{{ item }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - git
  retries: "{{ remote_package_retries }}"
  register: apt_result
  until: apt_result is succeeded
  become: True

- name: "Install S3 requirements"
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore
  when: application_s3_bucket | length > 0
  retries: "{{ remote_package_retries }}"
  register: pip_result
  until: pip_result is succeeded
  become: True
