FROM ubuntu:18.04

RUN apt-get update -qq && \
    apt-get install -qq sudo python3-apt python3-pycurl python3-pip python3-dev \
                        libffi-dev libssl-dev && \
    pip3 install -U setuptools && \
    pip3 install -q ansible==2.9.1

WORKDIR /tmp/ansible-role-an-application
COPY  .  /tmp/ansible-role-an-application

RUN useradd -m deploy
RUN echo localhost > inventory

RUN ansible-playbook -i inventory -c local tests/playbook.yml
