---
- name: "Send key to remote deploy user"
  copy:
    src: "files/deploy_keys/{{ application_deploy_key }}"
    dest: "{{ application_prefix }}/{{ application_name }}/shared/.ssh_deploy_key"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0600

- name: "Clonning project repo"
  git:
    repo: "{{ application_repository }}"
    dest: "{{ application_prefix }}/{{ application_name }}/releases/{{ timestamp.stdout }}"
    accept_hostkey: true
    depth: 1
    key_file: "{{ application_prefix}}/{{ application_name }}/shared/.ssh_deploy_key"
    version: "{{ application_release_version }}"
  become_user: "{{ application_user }}"
