---
- name: "Download project"
  get_url:
    url: "{{ application_url }}"
    dest: "{{ application_prefix }}/{{ application_name }}/releases/{{ timestamp.stdout }}/"
    headers: "{{ application_url_headers | default(omit) }}"
  become_user: "{{ application_user }}"
